name: My event Workflow
on:
  push:
    banches:
      - "master"
      - "main"
    paths:
      - "**.py"
jobs:
  model-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Build Model
        run: echo "Build model in CI Pipeline"
  model-cd:
    needs: model-ci
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Model
        run: echo "Deploy model in CD Pipeline"